# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MyPy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set up Evennia
      run: |
          git clone https://github.com/evennia/evennia.git ../evennia
          pip install -e ../evennia
    - name: Test with MyPy
      run: |
        mypy --follow-imports=silent --namespace-packages --explicit-package-bases .
